language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "12"
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  cleanup: true
  keep_history: true
  token: $GITHUB_TOKEN
  local_dir: build/
  target_branch: gh-pages
  commit_message: "Deploy del proyecto"
  on:
    branch: master
